import { Signal, TrendingGroup, WeeklyReport } from "@/lib/types";

export const fallbackSignals: Signal[] = [
  {
    id: 9001,
    category: "AI breakthrough",
    importance_score: 92,
    opportunity_score: 9,
    trend_score: 86,
    action_recommendation: "Prototype one agent workflow around this pattern and watch adoption over the next week.",
    created_at: new Date().toISOString(),
    raw_title: "AI agents move from demos to production workflows",
    source: "radar",
    link: "https://news.ycombinator.com",
    tags: ["ai", "agents", "automation"],
    published_at: new Date().toISOString(),
    image_url: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1200&q=80",
    image_alt: "AI agents news image",
    summary: {
      headline: "Agentic workflows are becoming practical for small teams",
      what_happened: "Developer and startup communities are converging around agent workflows that connect search, code, browser tasks, and business ops.",
      why_it_matters: "This raises the ceiling for solo founders and small teams by turning repeatable knowledge work into software-like processes.",
      why_you_should_care: "You can turn one painful recurring task into a differentiated internal tool or customer-facing feature.",
      action_recommendation: "Pick one workflow you do weekly and sketch an agent version today.",
      opportunity_score: 9,
    },
  },
  {
    id: 9002,
    category: "open-source trend",
    importance_score: 88,
    opportunity_score: 8,
    trend_score: 81,
    action_recommendation: "Track the repo, inspect issues, and look for integration gaps.",
    created_at: new Date().toISOString(),
    raw_title: "Open-source AI infrastructure keeps fragmenting into sharper tools",
    source: "github",
    link: "https://github.com/trending",
    tags: ["open-source", "developer", "inference"],
    published_at: new Date().toISOString(),
    image_url: "https://images.unsplash.com/photo-1556075798-4825dfaaf498?auto=format&fit=crop&w=1200&q=80",
    image_alt: "Open source AI news image",
    summary: {
      headline: "AI infrastructure niches are still early enough to enter",
      what_happened: "Trending repositories show steady demand for better evals, routing, observability, inference, and workflow tooling.",
      why_it_matters: "Fragmentation creates integration pain, and integration pain is often a startup wedge.",
      why_you_should_care: "A small wrapper, hosted dashboard, or managed workflow can become a useful paid product.",
      action_recommendation: "Find one popular repo with unresolved setup or monitoring complaints.",
      opportunity_score: 8,
    },
  },
  {
    id: 9003,
    category: "coding trend",
    importance_score: 83,
    opportunity_score: 7,
    trend_score: 74,
    action_recommendation: "Update your stack watchlist and test the best-supported path.",
    created_at: new Date().toISOString(),
    raw_title: "Full-stack TypeScript apps keep moving toward simpler deployment",
    source: "rss",
    link: "https://vercel.com/blog",
    tags: ["coding", "nextjs", "deployment"],
    published_at: new Date().toISOString(),
    image_url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80",
    image_alt: "Developer tools news image",
    summary: {
      headline: "Framework and hosting defaults are compressing MVP timelines",
      what_happened: "The latest app stacks emphasize type safety, server components, managed databases, and fewer custom deployment steps.",
      why_it_matters: "Speed compounds when teams spend less time wiring infrastructure and more time learning from users.",
      why_you_should_care: "You can ship smaller experiments faster without sacrificing a credible production path.",
      action_recommendation: "Use the simplest managed path for the next MVP unless scale already demands otherwise.",
      opportunity_score: 7,
    },
  },
  {
    id: 9004,
    category: "startup opportunity",
    importance_score: 79,
    opportunity_score: 8,
    trend_score: 69,
    action_recommendation: "Interview five operators who still copy data between tools.",
    created_at: new Date().toISOString(),
    raw_title: "Boring business workflows remain rich AI automation targets",
    source: "reddit",
    link: "https://www.reddit.com/r/startups/",
    tags: ["startups", "automation", "ops"],
    published_at: new Date().toISOString(),
    image_url: "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=80",
    image_alt: "Startup automation news image",
    summary: {
      headline: "Unsexy operations problems are becoming AI product opportunities",
      what_happened: "Operators keep describing repeated handoffs across spreadsheets, CRMs, inboxes, and dashboards.",
      why_it_matters: "These workflows have clear ROI and buyers who already feel the pain.",
      why_you_should_care: "A narrow automation product can beat a generic assistant when it owns one workflow end to end.",
      action_recommendation: "Look for one repeated approval, reporting, or reconciliation loop.",
      opportunity_score: 8,
    },
  },
  {
    id: 9005,
    category: "hiring trend",
    importance_score: 74,
    opportunity_score: 6,
    trend_score: 63,
    action_recommendation: "Map the skill gap and adjust learning or hiring priorities.",
    created_at: new Date().toISOString(),
    raw_title: "AI product engineering roles reward systems thinking",
    source: "hackernews",
    link: "https://news.ycombinator.com/jobs",
    tags: ["jobs", "ai", "engineering"],
    published_at: new Date().toISOString(),
    image_url: "https://images.unsplash.com/photo-1518152006812-edab29b069ac?auto=format&fit=crop&w=1200&q=80",
    image_alt: "AI engineering news image",
    summary: {
      headline: "The market wants engineers who can own AI features end to end",
      what_happened: "Hiring signals increasingly blend product judgment, backend reliability, evals, and frontend polish.",
      why_it_matters: "AI features are no longer isolated model calls; they are product systems.",
      why_you_should_care: "Building full-stack AI product proof will matter more than just prompting or model familiarity.",
      action_recommendation: "Create one portfolio workflow with evals, auth, persistence, and deployment.",
      opportunity_score: 6,
    },
  },
];

export const fallbackTrending: TrendingGroup[] = [
  { section: "Trending Opportunities", signals: fallbackSignals.slice(0, 3) },
  { section: "Open Source Trends", signals: fallbackSignals.slice(1, 3) },
  { section: "Startup Trends", signals: [fallbackSignals[3], fallbackSignals[0]] },
  { section: "Latest AI Breakthroughs", signals: [fallbackSignals[0], fallbackSignals[4]] },
];

export const fallbackWeeklyReport: WeeklyReport = {
  headline: "Your highest-value opportunity signals this week",
  executive_summary: "AI agents, open-source infrastructure, and workflow automation remain the strongest startup-relevant patterns.",
  top_categories: ["AI breakthrough", "open-source trend", "startup opportunity"],
  signals: fallbackSignals,
};
